# frozen_string_literal: true

source 'https://rubygems.org/'

ruby '~> 3.3'

gem 'json'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-sinatra'
gem 'opentelemetry-sdk'
gem 'puma'
gem 'rack'
gem 'rackup'
gem 'sinatra'
